### ISSUE TITLE
Using an optional or splat route near root leads to crash due to redundant pattern match

### ISSUE THREAD

**Issue by j-maas** [dillonkearns/elm-pages-v3-beta#4]
When I use a optional or splat route near the root, the generated code already covers all cases making the catchall redundant. This leads to a crash with the following error:

```
-- REDUNDANT PATTERN --------------- /home/jojo/Code/route-redundant-pattern-reproduction/elm-stuff/elm-pages/.elm-pages/Main.elm

The 2nd pattern is redundant:

552|                     case thisActionData of
553|                         ActionDataIndex__ justActionData ->
554|                             Just justActionData
555| 
556|>                        _ ->
557|                             Nothing

Any value with this shape will be handled by a previous pattern, so it should be
removed.,
-- REDUNDANT PATTERN --------------- /home/jojo/Code/route-redundant-pattern-reproduction/elm-stuff/elm-pages/.elm-pages/Main.elm

The 2nd pattern is redundant:

329|                                                 case andThenUnpack of
330|                                                     ActionDataIndex__ thisActionData ->
331|                                                         Just thisActionData
332| 
333|>                                                    otherwise_1_0_1_2_3_3_0 ->
334|                                                         Nothing

Any value with this shape will be handled by a previous pattern, so it should be
removed.,
-- REDUNDANT PATTERN --------------- /home/jojo/Code/route-redundant-pattern-reproduction/elm-stuff/elm-pages/.elm-pages/Main.elm

The 2nd pattern is redundant:

482|                                                         case mapUnpack0 of
483|                                                             ActionDataIndex__ justActionData ->
484|                                                                 Just
485|                                                                     justActionData
486| 
487|>                                                            otherwise_1_1_1_0_0_1_7_2_4_0 ->
488|                                                                 Nothing

Any value with this shape will be handled by a previous pattern, so it should be
removed.
```

This happens if I use a splat route at the root, like /SPLAT__. Other variations like /Lang_/SPLAT__ had the same problem.

I have made a [reproduction repository](https://github.com/j-maas/route-redundant-pattern-reproduction).

**Comment by j-maas** [comment]
I hope this is the right repo to open the issue on.

In my case I work around it, since I can make a /de/SPLAT__ and a /en/SPLAT__ route. It's a bit redundant, but it works for now.

~I will also have a look, if I can maybe open a PR to fix this.~ The codegen code is too dense for me...

**Comment by dillonkearns** [comment]
Oh yes, this makes sense, I understand where the issue is. I'll work on a fix. Thanks so much for finding and reporting this!

**Comment by dillonkearns** [comment]
Could you share the list of files in your `app/Route/` folder that was able to reproduce this, by the way?

**Comment by dillonkearns** [comment]
Oh, never mind, looks like you made a reproduction here: https://github.com/j-maas/route-redundant-pattern-reproduction/tree/main/app/Route. Thanks!

**Comment by j-maas** [comment]
I've updated the reproduction repository. ;)

**Comment by dillonkearns** [comment]
Amazing, thank you! 🙏

**Comment by dillonkearns** [comment]
Hello @j-maas, I tried this out with the latest and it seems to be working now. Would you mind checking if it's working for the initial use case you ran into this with as well? Thank you!

**Comment by dillonkearns** [comment]
I created a PR to update to the latest beta: https://github.com/j-maas/route-redundant-pattern-reproduction/pull/1

**Comment by j-maas** [comment]
I'm really busy right now, but I'll try to have a look on the weekend.

**Comment by j-maas** [comment]
Merging your PR, the issue seems to be fixed; I can open the page without errors on my repro repo. Thank!

Feel free to close this issue. :)

**Comment by dillonkearns** [comment]
Okay great, thanks again for reporting the issue, and thank you for confirming the fix!
